### ISSUE TITLE
Sensor not showing data on the SmartApp

### ISSUE THREAD

**Issue by Nijmegen-Geluid** [smartemission/smartemission#112]
The sensor lights orange and flashes every 11 seconds white.
But no data is seen on the SmartApp.
Is it possible to send an mail or SMS to the citizen? So that the citizen can reset the sensor.

**Comment by justb4** [comment]
First: which sensor number?

We currently have no registration of emails coupled to sensor numbers. At least the platform does not have this information. Once we have this info we can setup some kind of "uptime" checker.

**Comment by Nijmegen-Geluid** [comment]
Okay. Very good. We make a list.
Are there any costs?

**Comment by justb4** [comment]
Yes offcourse there are costs. Depends a bit on the solution:

- simple: have an external uptimechecker per sensor like GeoHealthCheck or UptimeRobot with email-address from user
- full: maintain users and sensors in platform with notifications

Please open separate issue with title like "Notify sensor-user when sensor data is not updated"
