### ISSUE TITLE
Niet aangesloten geluidsensor geeft wel een dB waarde

### ISSUE THREAD

**Issue by Hans-Nouwens** [smartemission/smartemission#113]
De geluidssensor van unit met de ID's 0004A30B00013301 (1305167546888961) | sc | 14607 | 20040007 | 
is niet aangesloten. Op de Smart App staat wel een geluidswaarde.

**Comment by justb4** [comment]
Volgens mijn gegevens werkt komt geluid voor station 20040007 goed door, ook te zien in ruwe data Viewer:

![image](https://user-images.githubusercontent.com/582630/41028305-6b062380-6979-11e8-982b-f344ae769608.png)

Dit issue gesloten, indien nog steeds probleem, graag aantonen en issue heropenen.
