### ISSUE TITLE
Jose 053 not seen on Whale viewer

### ISSUE THREAD

**Issue by Nijmegen-Geluid** [smartemission/smartemission#119]
Jose 053 not seen on Whale viewer
And is seen on other viewers

**Comment by justb4** [comment]
Station 53 has been moved from the Whale server Data Collector to the Intemo server Data Collector. 

There the data is visible:
https://josene.intemo.com/sensors/list/

The full list of moved sensors: 22,29,36,37,49,53,83,82,85,89,92,102,126,133.
